#Introduction-------------------------------------------------------------------

#As EthoVision XT 9 incorrectly detects movement when the larva is stationary,
#This script serves to distinguish active crawling from reorientation episodes
#using data generated by the software. A reorientation episode here is
#defined as a change of sign in the heading value twice within 12 seconds or
#less.

#Developed by Azan Ahmed - 09/03/2023

#Preamble-----------------------------------------------------------------------

options(warn = 2)

library(dplyr)
library(readxl)
library(stringr)
library(crayon)

#Specify which analysis folder to look into.
analysis_number <- "1"
setwd(paste("path/to/your/data", analysis_number, sep = ""))
path_cwd <- getwd()

#Create a summary table which will hold all the outputs for each sheet.
summary_df <- data.frame(matrix(ncol = 7, nrow = 0))
column_name <- c("trial", "arena", "percentage_time_spent_moving", "headshakes",
                 "max_speed", "mean_speed", "median_speed")
colnames(summary_df) <- column_name


slate_dark_gray <- make_style("slategray4")
slate_gray <- make_style("slategray3")
light_blue <- make_style("lightblue1")

cat(light_blue$bold("Initializing script...", "\n"))

#Access each file and sheet-----------------------------------------------------

my_xlsx_files <- dir(path=path_cwd)
for (file in my_xlsx_files){
  trial_file_name <- tools::file_path_sans_ext(file)
  trial_number <- str_extract(trial_file_name, "\\d+$")
  
  arena <- excel_sheets(file)
  for (sheets in arena){
    arena_sheet_name <- sheets
    arena_number <- str_extract(arena_sheet_name, "\\d+")
    
#Part 1: Preparing for analysis-------------------------------------------------
    
    #Set data range and calculate threshold
    #FIXME This section of the code has only been verified to identify 2.5 and
    #3.75 FPS.
    
    #(BUG)when col_names = FALSE, R creates new column names
    #and will print out a message each time it does.
    #Suppress message prevents read_excel from printing out the message.
    suppressMessages(
      arena_df <- read_excel(file, sheets, range = cell_cols(9:10),
                             col_names = FALSE, col_types = "text")
    )
    arena_df <- arena_df[-c(1:3),]
    colnames(arena_df) <- c("heading", "speed")
    #Creates new column to track frames with valid_movement. Initially, all
    #cases will be labelled with 2.Valid movement is tracked as 1, and invalid
    #movement is tracked as 0. 2 will indicate the observation has not been
    #analysed properly.
    arena_df$valid_movement <- 2
    arena_df$observation <- 1:nrow(arena_df)
    if (arena_number == "1"){
      fps <<- ((tail(arena_df$observation, n = 1)) - 1)/300
      threshold <<- (round(12*fps)) + 1
      cat(slate_dark_gray("The FPS for trial", trial_number, "is calculated to",
                          "be",paste0(fps, ": adjusting threshold to ",
                                      threshold, "\n")))
    }
    cat("Processing trial", trial_number,"arena", paste0(arena_number, "...",
                                                         "\n"))
    
    #Set up variables.
    missing_count <<- 0
    observation_count <<- 0 #Tracks the observation number that is 
    #currently analysed.
    successive_count <<- 0 #Counts the number of successive cases that
    #has the same sign.
    previous_sign <<- 0 #Stores the heading value of the previous case.
    wiggle_count <<- 0 #Counts how many head adjustments the larvae performs.
    check_valid_movement_change <<- 0
    present_data_count <<- 0#tracks the number of non missing data in
    #between missing data.
    not_missing_count <<- 0
    sign_change <<- FALSE 
    discard_arena <<- FALSE 
    recently_missing <<- TRUE
    missing_data <<- FALSE
    start_sign_change_missing_loop <<- FALSE
    
#Part 2: Analyse current case---------------------------------------------------

    for (row in 1:nrow(arena_df)) { 
      
      current_sign <- arena_df[row, "heading"]
      
      if (((observation_count == 0) |#When analysing the first observation,
           #there is no previous observation to
           #compare it, so assume movement is valid.
           (current_sign >= 0 & previous_sign >= 0) |
           (current_sign < 0 & previous_sign < 0))& 
          (current_sign != "-")){
        sign_change <<- FALSE
        missing_data <<- FALSE
        successive_count <<- successive_count + 1
        present_data_count <<- present_data_count + 1
        not_missing_count <<- not_missing_count + 1
      }
      
      else if ((current_sign == "-")){
        missing_data <<- TRUE
        missing_count <<- missing_count + 1
      }
      
      else {
        sign_change <<- TRUE 
        missing_data <<- FALSE
        present_data_count <<- present_data_count + 1
        not_missing_count <<- not_missing_count + 1
      }
      
      if ((previous_sign == "-") & (current_sign != "-")){
        recently_missing <<- TRUE
        sign_change <<- FALSE
        missing_data <<- FALSE
        successive_count <<- 1
        present_data_count <<- 1
      }
      
      if ((previous_sign != "-") & (current_sign == "-")){
        start_sign_change_missing_loop <<- TRUE
      }
      
      previous_sign <<- current_sign
      observation_count <<- observation_count + 1
      
#Part 3: Process current case---------------------------------------------------
      
      #if there is a sign change and the successive amount of cases adds up to
      #12 seconds or less, the larva most likely stopped moving and so speed
      #is invalid.
      if ((sign_change == TRUE) & (successive_count <= threshold)){
        wiggle_count <<- wiggle_count + 1
        
        #TODO:Create a function based on this while loop
        while (successive_count != 0) {
          observation_to_change <- observation_count - successive_count
          arena_df[arena_df$observation == observation_to_change,
                   'valid_movement'] <- 0
          successive_count <<- successive_count - 1
        }
        
        #Assume current case is valid.
        successive_count <<- 1
        arena_df[arena_df$observation == observation_count, 'valid_movement'] <-
          1
      }
      
      #If there is a sign change but the successive amount of cases
      #add up to longer than 12 seconds, this is most likely a direction change
      #rather than a reorientation episode,so speed is valid.
      else if ((sign_change == TRUE) & (successive_count > threshold)){
        successive_count <<- 1
        arena_df[arena_df$observation == observation_count, 'valid_movement'] <-
          1
      }
      
      #If there is no sign change, the larva did not stop moving so 
      #speed is valid.
      else {
        arena_df[arena_df$observation == observation_count, 'valid_movement'] <-
          1
      }
      
      #With missing data in between present data less than 12 seconds,
      #it is not possible to discern whether the movements recorded are valid
      #so assume they are invalid and dont consider them for time spent moving.
      if ((recently_missing == TRUE) & (missing_data == TRUE) &
          (present_data_count <= threshold)){
        recently_missing <<- FALSE
        successive_count <<- 0
        not_missing_count <<- not_missing_count - present_data_count
        
        
        while (present_data_count != 0){
          observation_to_change <<- observation_count - present_data_count
          arena_df[arena_df$observation == observation_to_change,
                   'valid_movement'] <- 0
          present_data_count <<- present_data_count - 1
        }
      }
      
      #If sign changes 12 seconds before missing data appears, it is not
      #possible to discern whether the cases are valid or not, so assume
      #they are invalid and don't consider them for time spent moving.
      if ((missing_data == TRUE) & (successive_count <= threshold) &
          (start_sign_change_missing_loop == TRUE)){
        start_sign_change_missing_loop <<- FALSE
        not_missing_count <<- not_missing_count - successive_count
        
        while (successive_count != 0) {
          observation_to_change <<- observation_count - successive_count
          arena_df[arena_df$observation == observation_to_change,
                   'valid_movement'] <- 0
          successive_count <<- successive_count - 1
        }
      }
      #if sign doesn't change 12 seconds before missing data appears, we can
      #discern whether cases are valid or not.
      else if ((missing_data == TRUE) & (successive_count > threshold) &
               (start_sign_change_missing_loop == TRUE)){
        start_sign_change_missing_loop <<- FALSE
      }
      
      #If a "-" is detected, consider the current case is invalid.
      if (missing_data == TRUE){
        arena_df[arena_df$observation == observation_count, 'valid_movement'] <-
          0
        successive_count <<- 0
      }
      
      #If more than 12 seconds passed since the last missing data,
      #we can discern whether the movements recorded are valid or not.
      if ((recently_missing == TRUE) & (present_data_count > threshold)){
        recently_missing <<- FALSE
      }
      
      #Check if the current case has been analysed properly.
      check_valid_movement_change <<- arena_df[row, 'valid_movement']
      if (check_valid_movement_change == 2){
        cat(red('WARNING: trial', trial_number, 'arena', arena_number,
                "observation", observation_count,
                "has not been analysed correctly", "\n"))
      }
    }
    
#Part 4: Process arena----------------------------------------------------------
    
    #If sign changes within the last 12 seconds,
    #we cannot be sure if movement is valid in that duration
    #so consider all movement in that period as invalid and don't consider them
    #for time spent moving.
    if (successive_count < threshold){
      not_missing_count <<- not_missing_count - successive_count
      
      while (successive_count != -1){
        observation_to_change <- observation_count - successive_count
        arena_df[observation_to_change, 3] <- 0
        successive_count <<- successive_count - 1
      }
    }
    
    #Check if arena is empty.
    if (missing_count == observation_count){
      cat(slate_gray("Empty arena? Omitting trial", trial_number, "arena",
                     arena_number, "from results...", "\n"))
      discard_arena <- TRUE
    }
    
    #Check if arena is tracked properly.
    else if (not_missing_count == 0){
      cat(slate_gray("There is too many missing data in trial", trial_number,
                     "arena", paste0(arena_number, "!"),
                     "discarding it from results...", "\n"))
      discard_arena <- TRUE
    }
    
#Part 5: Obtain summary values--------------------------------------------------
    
    #Store summary data for arenas that are not discarded.
    if (discard_arena == FALSE){
      valid_df <- arena_df %>%
        filter(valid_movement == 1)
      
      #Get %time spent moving.
      total_movement <- sum(valid_df$valid_movement)
      proportion_movement <- (total_movement/not_missing_count)*100
      
      #median and max function will return with NA and -Inf respectively 
      #if there are no valid movements, so assign median and max values to 0.
      if (proportion_movement == 0){
        largest_speed <- 0
        middle_speed <- 0
        average_speed <- 0
        cat(slate_gray("No movement detected in trial", trial_number, "arena",
                       paste0(arena_number, "!"), "\n"))
      }
      else {
        valid_df$speed = as.numeric(as.character(valid_df$speed),
                                    ' ')
        largest_speed <- max(valid_df$speed)
        middle_speed <- median(valid_df$speed)
        average_speed <-mean(valid_df$speed)
      }
      summary_df[nrow(summary_df) + 1,] = list(trial = trial_number,
                                               arena = arena_number,
                                               percentage_time_spent_moving = 
                                                 proportion_movement,
                                               headshakes = wiggle_count,
                                               max_speed = largest_speed,
                                               mean_speed = average_speed,
                                               median_speed =
                                                 middle_speed)
    }
  }
}

#Store analysis results---------------------------------------------------------

#Some arenas may be unsuitable for analysis and should be excluded from results.
#The list of excluded arenas is stored in a separate excel file, and is summoned
#by the script so we can remove these arenas from summary_df before storing the
#results in a new file.
cat(slate_dark_gray("Removing exlcuded arenas...", "\n"))
exclusion_list <- read_excel(path = 
                               "path/to/your/data", range = cell_cols("A:B"),
                             col_types = "text")

summary_df <- summary_df %>%
  anti_join(exclusion_list, by = join_by(trial, arena))

#Create a new csv file which stores the results of the analysis.
write.csv(summary_df, paste(
  "path/to/your/data", "\\Crawl test analysis/analysis ", analysis_number,
  ".csv", sep = ""), row.names = FALSE)

#Create a new csv file which stores the results of the analysis,
#omitting arenas with no movement detected.
write.csv(summary_df %>%
            filter(percentage_time_spent_moving != 0), paste(
              "path/to/your/data", "\\Crawl test analysis/zero free analysis ",
              analysis_number, ".csv", sep = ""), row.names = FALSE)

cat(green$bold("Data processing complete!"))